-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('FRIEND_ACCEPTED', 'FRIEND_REQUEST', 'NEW_CHALLENGE', 'DAILY_CHALLENGE', 'WEEKLY_CHALLENGE', 'COMMUNITY_BANNED', 'COMMUNITY_UNBANNED', 'GROUP_BANNED', 'GROUP_UNBANNED', 'SPOT_SUGGESTION_APPROVED', 'SPOT_SUGGESTION_REJECTED') NOT NULL;

